echo Installing Git...
winget install --id Git.Git -e --silent
echo Installing cURL...
winget install --id cURL.cURL -e --silent
echo Installing TightVNC...
msiexec /i tightvnc-2.8.85-gpl-setup-64bit.msi
echo Installing Python
"Python 3.13 Installer.exe"
echo Installing websockify...
pip install websockify --user
